# Generated by Django 2.0 on 2020-04-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hometask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('name', models.CharField(max_length=100, verbose_name='Имя файла')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл с заданием')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='UserHometask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'assigned'), ('D', 'done'), ('C', 'change_required'), ('S', 'success')], default='A', max_length=2)),
                ('hometask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hometasks.Hometask', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Статус задания',
                'verbose_name_plural': 'Статусы задания',
            },
        ),
    ]
