# Generated by Django 2.0 on 2020-04-22 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_usergroup_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hometasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhometask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='hometask',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group', verbose_name='Задание'),
        ),
    ]
